type EthereumHeader {
    parentHash:            String
    sha3Uncles:            String
    miner:                 String
    stateRoot:             String
    transactionsRoot:      String
    receiptsRoot:          String
    logsBloom:             String
    difficulty:            String
    number:                String 
    gasLimit:              String
    gasUsed:               String
    timestamp:             String
    extraData:             String
    baseFeePerGas:         String
    withdrawalsRoot:       String
}

type EthereumTransaction {
    type:                 Int
    chainId:              String
    from:                 String
    gas:                  String
    gasPrice:             String
    maxPriorityFeePerGas: String
    maxFeePerBlobGas:     String
    maxFeePerBlobGas:     String
    accessList:           [EthereumAccessList]
    blobVersionedHashes:  [String]
    hash:                 String
    input:                String
    nonce:                String
    to:                   String
    value:                String
    v:                    String
    r:                    String
    s:                    String
    yParity:              Int
}

type EthereumAccessList {
    transaction: EthereumTransaction @primary
    address:     String
    storageKeys: [String]
}

type EthereumWithdrawal {
    index:            String
    amount:           String
    validatorIndex:   String
    address:          String
}