type EthereumHeader {
    parentHash:            String
    sha3Uncles:            String
    miner:                 String
    stateRoot:             String
    transactionsRoot:      String
    receiptsRoot:          String
    logsBloom:             String
    difficulty:            String
    number:                String 
    gasLimit:              String
    gasUsed:               String
    timestamp:             String
    extraData:             String
    baseFeePerGas:         String
    withdrawalsRoot:       String
}

type EthereumTransaction {
    type:                 String
    chainId:              String
    gas:                  String
    gasPrice:             String
    maxPriorityFeePerGas: String
    maxFeePerBlobGas:     String
    accessList:           [EthereumAccessList]
    blobVersionedHashes:  [String]
    input:                String
    nonce:                String
    to:                   String
    value:                String
    v:                    String
    r:                    String
    s:                    String
    yParity:              String
}

type EthereumAccessList {
    transaction: EthereumTransaction @primary
    address:     String
    storageKeys: [String]
}

type EthereumWithdrawal {
    index:            String
    amount:           String
    validatorIndex:   String
    address:          String
}

type EthereumReceipt {
    root:            String
    cumulateGasUsed: String
    bloom:           String
    logs:            [EthereumLog]
}

type EthereumLog {
    receipt: EthereumReceipt @primary
    address: String
    topics:  [String]
    data:    String
}

type EthereumTransactionsProof {
    transactions: [String]
}

type EthereumUnclesProof {
    uncles: [String]
}

type EthereumWithdrawalsProof {
    withdrawals: [String]
}

type EthereumReceiptsProof {
    receipts: [String]
}
